-- CREATE TABLES

-- public.cliente definition
CREATE TABLE cliente
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_fim    timestamp NULL,
    data_inicio timestamp NOT NULL,
    data_atualizacao  timestamp NULL,
    email       varchar(200) NOT NULL,
    nome        varchar(200) NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

-- public.produto definition
CREATE TABLE produto
(
    id           int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    codigo       varchar(200) NOT NULL,
    data_fim     timestamp NULL,
    data_inicio  timestamp NOT NULL ,
    data_atualizacao  timestamp NULL,
    nome         varchar(200) NOT NULL,
    preco        float8       NOT NULL,
    tipo_produto varchar(10)  NOT NULL,
    CONSTRAINT produto_pkey PRIMARY KEY (id)
);

-- public.pedido definition
CREATE TABLE pedido
(
    id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_fim    timestamp NULL,
    data_inicio timestamp NULL,
    total       float8 NULL,
    id_cliente  int8 NOT NULL,
    desconto    float8,
    situacao    varchar(10) NOT NULL,
    CONSTRAINT pedido_pkey PRIMARY KEY (id)
);

-- public.pedido foreign keys

ALTER TABLE pedido
    ADD CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id);

-- public.item_pedido definition
CREATE TABLE item_pedido
(
    id         int8   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    preco      float8 NOT NULL,
    quantidade int4 NULL,
    subtotal   float8 NULL,
    id_pedido  int8   NOT NULL,
    id_produto int8   NOT NULL,
    CONSTRAINT item_pedido_pkey PRIMARY KEY (id),
    CONSTRAINT item_pedido_quantidade_check CHECK ((quantidade >= 1))
);

-- public.item_pedido foreign keys

ALTER TABLE item_pedido
    ADD CONSTRAINT fk_pedido FOREIGN KEY (id_pedido) REFERENCES pedido (id);
ALTER TABLE item_pedido
    ADD CONSTRAINT fk_produto FOREIGN KEY (id_produto) REFERENCES produto (id);

------------------------------------------------------------------------------------------------------------------------

-- INSERTS

-- Dando carga na tabela de clientes
INSERT INTO cliente
    (data_atualizacao, data_fim, data_inicio, email, nome)
values (null, null, '2022-12-12 01:01:09.977', 'cliente1@gmail.com', 'cliente 1'),
       (null, null, '2022-12-12 01:01:09.977', 'cliente2@gmail.com', 'cliente 2'),
       (null, null, '2022-12-12 01:01:09.977', 'cliente3@gmail.com', 'cliente 3'),
       (null, null, '2022-12-12 01:01:09.977', 'cliente4@gmail.com', 'cliente 4'),
       (null, null, '2022-12-12 01:01:09.977', 'cliente5@gmail.com', 'cliente 5'),
       (null, null, '2022-12-12 01:01:09.977', 'cliente6@gmail.com', 'cliente 6');

-- Dando carga na tela de produtos
INSERT INTO produto
    (data_atualizacao, data_fim, data_inicio, nome, preco, codigo, tipo_produto)
VALUES (null, null, '2022-12-05 11:01:09.977', 'produto1', 15.0, 'cod0010', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto2', 15.0, 'cod0011', 'SERVICO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto3', 15.0, 'cod0012', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto4', 15.0, 'cod0013', 'SERVICO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto5', 15.0, 'cod0014', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto6', 15.0, 'cod0015', 'SERVICO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto7', 15.0, 'cod0016', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto8', 15.0, 'cod0017', 'SERVICO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto9', 15.0, 'cod0018', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto10', 15.0, 'cod0019', 'SERVICO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto11', 15.0, 'cod0020', 'PRODUTO'),
       (null, null, '2022-12-05 11:01:09.977', 'produto12', 15.0, 'cod0021', 'SERVICO');

-- Dando carga na tabela de pedidos
INSERT INTO pedido
    (data_fim, data_inicio, id_cliente, total, desconto, situacao)
VALUES (null, '2022-12-13 06:01:09.977', 1, 0.0, 0.0, 'FECHADO'),
       (null, '2022-12-13 06:01:09.977', 2, 0.0, 0.0, 'FECHADO'),
       (null, '2022-12-13 06:01:09.977', 3, 0.0, 0.0, 'FECHADO'),
       (null, '2022-12-13 06:01:09.977', 4, 0.0, 0.0, 'FECHADO'),
       (null, '2022-12-13 06:01:09.977', 5, 0.0, 0.0, 'FECHADO'),
       (null, '2022-12-13 06:01:09.977', 6, 0.0, 0.0, 'FECHADO');

-- Dando carga na tabela de itens do pedido
INSERT INTO item_pedido
    (preco, quantidade, id_pedido, id_produto, subtotal)
VALUES (35.0, 1, 1, 1, 0),
       (75.0, 2, 2, 2, 0),
       (25.0, 3, 3, 3, 0),
       (80.0, 4, 4, 4, 0),
       (65.0, 5, 5, 5, 0),
       (48.0, 6, 6, 6, 0),
       (38.0, 1, 1, 1, 0),
       (71.0, 2, 2, 2, 0),
       (55.0, 3, 3, 3, 0),
       (60.0, 4, 4, 4, 0),
       (30.0, 5, 5, 5, 0),
       (90.0, 6, 6, 6, 0);
